steps:
  - id: install_packages
    dir: 'static'
    name: 'gcr.io/cloud-builders/npm:current'
    args:
      - 'install'
  - id: build
    dir: 'static'
    name: 'gcr.io/cloud-builders/npm:current'
    args:
      - 'run'
      - 'build'
    env:
      - BLUMHOUSE_TWITTER_NAME=mattdsteele
  - id: deploy
    dir: 'static'
    name: gcr.io/cloud-builders/gsutil
    args:
      [
        '-m',
        'rsync',
        '-r',
        '-c',
        '-j',
        'html,css,js',
        '-d',
        '_site',
        'gs://twitter-archive.steele.blue',
      ]
