steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'functions',
        'deploy',
        'purge-mattdsteele',
        '--trigger-topic',
        'blumhouse',
        '--runtime',
        'go111',
        '--entry-point',
        'CloudPurge',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'functions',
        'deploy',
        'purge-firedhuskers',
        '--trigger-topic',
        'blumhouse',
        '--runtime',
        'go111',
        '--entry-point',
        'CloudPurge',
      ]
